title: Mert Melih Albay
theme: jekyll-theme-minimal
logo: assets/image (2).png
description: |
  albaymertmelih@gmail.com
  Çankaya/ANKARA  
  
  <a href="assets/MertMelihAlbay_CV.pdf" class="cv-button" download>Özgeçmişimi İndir (PDF)</a>
